Fixed WithdrawFromCommonPool logic and ensured compatibliity with the interface
ADimoska/SOMASExtended pull request #19
Opened 2024-11-22 23:16 UTC by vedantvasugupta

Passed the value of the common pool to the withdraw function of the agent and created a function to handle all the withdrawals instead of implementing the logic in the runTurn function.

2024-11-25 20:04 UTC, arnavxkohli commented
LGTM @vedantvasugupta , The only addition I would suggest is randomising the order in which withdrawals are made. This would ensure that withdrawals aren't skewed.

2024-11-27 11:09 UTC, kishan-v commented
Same thoughts as [this](https://github.com/ADimoska/SOMASExtended/pull/32#discussion_r1858589481)

2024-11-27 11:10 UTC, kishan-v requested changes

2024-11-27 11:10 UTC, kishan-v commented on server/EnvironmentServer.go
> +		cs.ProcessWithdrawals() // Use the new withdrawal processing function
Same thoughts as [this](https://github.com/ADimoska/SOMASExtended/pull/32#discussion_r1858589481)

2024-11-28 20:28 UTC, kishan-v commented
@vedantvasugupta is this PR now obsolete since #44 has been merged in?

2024-11-29 12:14 UTC, closed without merging

2024-11-29 12:15 UTC, vedantvasugupta commented
Yes I have closed this pr