Overhaul team mapping
ADimoska/SOMASExtended pull request #28
Opened 2024-11-25 14:10 UTC by arnavxkohli

These changes deal with converting the raw team type into team pointers. Currently there is a bug caused by there not being any logic to declare a winner in case only one agent/one team is left. A work-around is used in the code, which otherwise runs fine:

```go
if team == nil {
    continue
}
```

2024-11-25 14:12 UTC, arnavxkohli commented
Would be nice if the people working on common pool updation can test their code with these updates before merging @kishan-v @nlewxxs

2024-11-25 17:24 UTC, nlewxxs requested changes
The common pools are indeed not working properly at the minute, probably a small change that needs to be made somewhere given the switch to pointers in team. 

Will take a look later tonight, unless @kishan-v gets there first.

2024-11-25 17:24 UTC, nlewxxs commented on server/EnvironmentServer.go
> +func (cs *EnvironmentServer) GetTeam(agentID uuid.UUID) *common.Team {
Are you not getting this error when you're running the code?
```
panic: interface conversion: *environmentServer.EnvironmentServer is not common.IServer: missing method GetTeam
```

You need to change the return type of: 

```go
GetTeam(agentID uuid.UUID) Team
```
to `*Team` in `IServer.go`. 

please run code before pushing :((

2024-11-25 17:52 UTC, kishan-v commented on server/EnvironmentServer.go
> +func (cs *EnvironmentServer) GetTeam(agentID uuid.UUID) *common.Team {
+1 
@nlewxxs is spot on here.

2024-11-25 18:53 UTC, arnavxkohli commented on server/EnvironmentServer.go
> +func (cs *EnvironmentServer) GetTeam(agentID uuid.UUID) *common.Team {
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/d3072219-dc6b-4ece-b038-64d755ef81c9">

2024-11-25 19:37 UTC, kishan-v commented
Fixed the bug so common pool increases/decreases as expected now

2024-11-25 19:38 UTC, kishan-v approved these changes

2024-11-26 01:24 UTC, Somewheref approved these changes
nice stuff

2024-11-26 09:31 UTC, nlewxxs approved these changes
Is there a reason we don't need `UpdateCommonPools()` anymore? I'm on my phone atm its hard to tell.

2024-11-26 11:59 UTC, kishan-v commented
> Is there a reason we don't need `UpdateCommonPools()` anymore? I'm on my phone atm its hard to tell.

I've re-added that behaviour of only updating the common pool after all agents have contributed/withdrawn in #31 . Please let me know what you think.

#31 would need to be merged into this PR (#28 ) before merging to main.

2024-11-26 12:19 UTC, kishan-v commented
There are now merge conflicts to main though :(

2024-11-26 23:17 UTC, merged