Updated withdrawl logic with random shuffle
ADimoska/SOMASExtended pull request #32
Opened 2024-11-26 13:26 UTC by vedantvasugupta

2024-11-26 13:32 UTC, kishan-v commented
@vedantvasugupta Please base the withdrawal order shuffling on the reworked RunTurn in #31

2024-11-26 13:56 UTC, kishan-v requested changes

2024-11-26 13:56 UTC, kishan-v commented on server/EnvironmentServer.go
> +
Please see my [comment](https://github.com/ADimoska/SOMASExtended/pull/32#issuecomment-2500814082)

2024-11-28 12:33 UTC, vedantvasugupta commented on server/EnvironmentServer.go
> +
Hi @kishan-v  that branch has been deleted

2024-11-28 14:05 UTC, closed without merging

2024-11-28 14:06 UTC, vedantvasugupta commented
Opening a new pr for this