Team forming: all agents refuse to join a team #59
ADimoska/SOMASExtended pull request #70
Opened 2024-11-29 17:04 UTC by sodabreak

2024-12-01 01:24 UTC, arnavxkohli requested changes

2024-12-01 01:24 UTC, arnavxkohli commented on server/EnvironmentServer.go
> +				for _, team := range cs.teams {
Perhaps we want to allot them round-robin based on team sizes? So the smallest team is allotted the agent first? Not sure how much this matters, but if we are sticking to fixed size teams this should be implemented

2024-12-01 23:57 UTC, nlewxxs commented on server/EnvironmentServer.go
> +				for _, team := range cs.teams {
I'm assuming teams cannot reject agents at this point? At the start of the iteration are all agent 'opinions' cleared? 

I'm trying to see if there is a case here where agents get rejected by the team during team formation but the server allocates them to the team anyway. 

I might be misunderstanding how team formation works.

2024-12-02 00:00 UTC, nlewxxs commented
I'm assuming teams cannot reject agents at this point? At the start of the iteration are all agent 'opinions' cleared?

I'm trying to see if there is a case here where agents get rejected by the team during team formation but the server allocates them to the team anyway.

I might be misunderstanding how team formation works.

2024-12-04 12:19 UTC, kushk2 approved these changes

2024-12-05 21:41 UTC, dhruvds12 commented
@sodabreak I think these changes were made in a later PR. 

Closing this PR

2024-12-05 21:41 UTC, closed without merging