Logging to log directory
ADimoska/SOMASExtended pull request #87
Opened 2024-12-02 18:56 UTC by kishan-v

2024-12-02 18:58 UTC, dhruvds12 approved these changes

2024-12-02 20:57 UTC, arnavxkohli requested changes

2024-12-02 20:57 UTC, arnavxkohli commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
Why're we changing the name of this function at all? It seems quite misleading to me. Isn't this function's purpose to decide the actual contribution of the agent which "decides" what to contribute?

2024-12-02 20:57 UTC, arnavxkohli commented on agents/ExtendedAgent.go
> +func (mi *ExtendedAgent) GetExpectedContribution() int {
See above.

2024-12-02 20:57 UTC, arnavxkohli commented on agents/ExtendedAgent.go
> +	withdrawal := instance.GetExpectedWithdrawal()
Same.

2024-12-02 23:06 UTC, kishan-v commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
1. Because the function I've renamed is indeed calculating the Expected Contribution. The function name is merely reflecting the choice of variable names e.g. line 178.
2. The value returns the expected contribution, which is in turn used to inform the Stated contribution and Actual contribution.
3. `DecideContribution` is completely ambiguous between Stated/Actual/Expected Contribution

2024-12-02 23:46 UTC, arnavxkohli commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
I think you don't need to "decide" what the expected contribution is right? As for stating the contribution that's handled by `StateContributionsToTeam()`.

Line 178 shows an idealistic agent which **decides** to contribute exactly what is expected of it. This decision will most definitely vary across AoAs and agent strategies. I think `GetActualContribution()` may be a better name? 

Look at line 53 in `EnvironmentServer` for the usage of this return value. It is used to deduct from the score of the agent (line 61 on `EnvironmentServer` where `agent.SetTrueScore()` is called.

@kishan-v

2024-12-03 00:02 UTC, mattstevenson22 commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
I second Arnav's reasoning here - is this not the function which decides what the agent contributes / withdraws? They do not have to contribute/withdraw what is *expected* of them by the AoA.

2024-12-03 09:51 UTC, dhruvds12 commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
The function `DecideContribution` has been removed from the interface as it is specific to each agent and is not called externally. Its inclusion forces teams to implement a function that is only relevant internally to their agent. Instead teams can define similar functionality within their agent class if needed. 

The server invokes `GetActualContribution` and `GetStatedContribution` on the agents, therefore these are the only functions needed in the Interface. The addition of `GetExpectedContribution` is more practical as this is required functionality for each agent. I agree that `GetExpectedContribution` could potentially be removed from the interface, as it can be independently implemented by each agent.

Happy to remove `GetExpectedContribution` from the base agent if we think that it won't be called externally, I thought it could be useful for auditing purposes. 

@kishan-v @arnavxkohli @mattstevenson22

2024-12-03 10:41 UTC, kishan-v commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
I think Dhruv is right here, `DecideContribution()` and `DecideWithdrawal()` are not invoked by the server and therefore don't need to be publicly accessible - they can be implemented as helper functions in each specific agent.

In this case we would remove those two functions from `ExtendedAgent` and `IExtendedAgent`.

I was originally thinking it is helpful to pre-implement agent functions which calculate the expected contribution/withdrawal since I assumed that would be an important input when deciding 'stated' and 'actual' contribution?

- E.g. My actual contribution would be either honest (give expected) or cheat (give slightly less than expected) but state that you gave equal to expected.

If we want to therefore keep them, we should rename `DecideContribution()` and `DecideWithdrawal()` to `GetExpectedContribution()` and `GetExpectedWithdrawal()`.

@mattstevenson22 @arnavxkohli @dhruvds12

2024-12-03 11:03 UTC, kishan-v commented on agents/ExtendedAgent.go
> +		contribution := instance.GetExpectedContribution()
Opened a new PR #90 for discussion.

I'll also create a new PR only for the logging changes.

2024-12-03 11:03 UTC, closed without merging