Fix allocateAoAs()
ADimoska/SOMASExtended pull request #88
Opened 2024-12-02 23:30 UTC by kishan-v

2024-12-03 07:18 UTC, nlewxxs requested changes

2024-12-03 07:18 UTC, nlewxxs commented on server/EnvironmentServer.go
>  				continue
Do dead agents remain in team.Agents? I thought they get removed?

2024-12-03 07:18 UTC, nlewxxs commented on server/EnvironmentServer.go
> +				tiedAoAs = append(tiedAoAs, aoa)
nice

2024-12-03 07:18 UTC, nlewxxs commented on server/EnvironmentServer.go
> +			for position, aoa := range aoaRanking {
This is basically a borda count no? Or can be made into one using very little changes - can we modify it to make it clear that that's what we did here?

2024-12-03 11:29 UTC, kishan-v commented on server/EnvironmentServer.go
> +			for position, aoa := range aoaRanking {
Yep it is a Borda count. I added a comment just above (in #L169). I can try to make it clearer though.

2024-12-03 11:58 UTC, kishan-v commented on server/EnvironmentServer.go
>  				continue
Yep good spot, those lines are unnecessary. Removed.

2024-12-03 12:01 UTC, kishan-v commented on server/EnvironmentServer.go
> -				continue
redundant code: dead agents are removed from `team.Agents`

2024-12-03 18:09 UTC, johanjino approved these changes

2024-12-03 18:09 UTC, johanjino commented on server/EnvironmentServer.go
>  			team.TeamAoA = common.CreateFixedAoA(1)
Shouldnt we randomise from existing AoAs if we end up here?

2024-12-03 18:09 UTC, johanjino commented on server/EnvironmentServer.go
>  			team.TeamAoA = common.CreateFixedAoA(1)
Thanks solved by @kishan-v

2024-12-03 18:40 UTC, dhruvds12 approved these changes

2024-12-04 06:01 UTC, nlewxxs approved these changes
hell yeah!

2024-12-04 09:48 UTC, merged