Upgrade allocateAoA()
ADimoska/SOMASExtended pull request #99
Opened 2024-12-03 22:38 UTC by EXiao3

Features: 

- Copeland Voting (Pairwise) 
- Followed by Borda Count if there is a tie
- Random AoA from remaining AoA's if there is still a tie.

Builds on the functionality introduced in PR #88.

Closes #25

2024-12-03 23:07 UTC, kishan-v requested changes

2024-12-03 23:07 UTC, kishan-v commented on server/EnvironmentServer.go
> +// Allocate AoA based on team votes;
I think it should be okay to remove this commented code, since this PR will merge ontop of this existing `allocateAoA()` and so it will be in the git history

2024-12-03 23:11 UTC, kishan-v commented
Pretty cool stuff! Always good to add some more things from the lectures.

2024-12-03 23:14 UTC, dhruvds12 requested changes

2024-12-03 23:14 UTC, dhruvds12 commented on server/EnvironmentServer.go
> +		agentRanking := cs.GetAgentMap()[agent].GetAoARanking()
Can `agentRanking` be changed to `agentAoARanking`

2024-12-03 23:14 UTC, dhruvds12 commented on server/EnvironmentServer.go
> +
Please can this be removed.

2024-12-03 23:15 UTC, johanjino commented on server/EnvironmentServer.go
> +
Cant have huge comments like this please?

2024-12-04 10:29 UTC, kishan-v approved these changes

2024-12-04 10:38 UTC, dhruvds12 approved these changes
LGTM!

2024-12-04 11:12 UTC, johanjino approved these changes
Lgtm

2024-12-04 11:51 UTC, merged